import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GuthenBlootsFont, ModernEraFont, RecoletaFont } from "@/assets/font";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Molvi Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased font-modernEra bg-background-secondary",
          RecoletaFont.variable,
          ModernEraFont.variable,
          GuthenBlootsFont.variable
        )}
      >
        <NextTopLoader color="#ff7e3d" height={3} showSpinner={false}/>
        {children}
      </body>
    </html>
  );
}
